# Generated by Django 3.1.5 on 2022-05-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_iletisimmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='modified',
            new_name='moderated',
        ),
    ]
